CREATE TABLE IF NOT EXISTS saved_jobs (
 id SERIAL PRIMARY KEY,
 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 job_id INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
 saved_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 notes TEXT
);
